/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://ntsf3hvkovgqldgpcnq6bhlrpe.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-xvnpsut7czbevazakomnicv4bm",
    "aws_cognito_identity_pool_id": "us-west-2:a8d8f984-0768-4b71-a670-c11c90336b88",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_iD5Fh9tUX",
    "aws_user_pools_web_client_id": "123k1399m2mebpl05p0vbce9j9",
    "oauth": {}
};


export default awsmobile;
